### ISSUE TITLE
降重才是王道，市场大大地

### ISSUE THREAD

**Issue by linux0ne** [tianlian0/paper_checking_system#1]
客观地讲，降重才是王道，你懂得！
只有这样的程序才有人用，你的支、微才有更多的收入。
加油吧。

不过，你这个查重的项目也是个好项目，只是你只是为了你们学校而建，需要使用你们学校的数据库，可并不是每个学校都有自己的论文库，或者说有很丰富的论文库的，所以高校与你合作的前景不知道如何。

如果你这个也可以通过网络，让广大网友自动和万方、CNKI进行比对，那就牛了。看你的功能描述貌似不是这样的，对吧？

**Comment by tianlian0** [comment]
学校一般都要对学生的毕业论文存档的，所以论文库可以说是每个学校都有。

**Comment by tianlian0** [comment]
主要toB，toC的话普通用户手里没有论文库也灭法真正使用用。高校会对所有学生的毕业论文留档，所以可以说高校都有自己的论文库。何况做降重有法律擦边球风险。

**Comment by tianlian0** [comment]
主要toB，toC的话普通用户手里没有论文库也没法真正使用用。高校会对所有学生的毕业论文留档，所以可以说高校都有自己的论文库。何况做降重有法律擦边球风险。

**Comment by tianlian0** [comment]
想写毕设可以看下我另一个项目哈：https://github.com/tianlian0/aided_writing
