### ISSUE TITLE
疑问：为什么不使用Parallel而手动处理线程的数量

### ISSUE THREAD

**Issue by Colin5887** [tianlian0/paper_checking_system#11]
请问您是基于什么考量，并没有使用Parallel来处理并发问题，而是手动让用户指线程数量。而且在线程数量的设置上还没有使用当前计算机所允许的最大线程。

还有一个问题是关于软件的交互方式的。我这里正在基于您的项目进行二次开发，不是很理解这种交互方式，因为实际使用的用户（学校的教师）对于多线程以及程序运行效率并没有什么深入的认识，绝大多数的用户都不会修改线程数量/字符数量上下限等设置，您是基于什么样的原因想要暴露这些接口给用户的呢？或者说，这个程序并不是您最新的版本（通过代码编译的程序所生成的报告与项目README中的图片不一致），交互设计的方式在新的程序中有所改变？

**Comment by tianlian0** [comment]
线程数在程序启动后根据CPU核心数自动设置，无需手工设置。“高级设置”选项卡下面的内容都都一样，您不需要的话直接隐藏掉就好。任何建议欢迎欢迎提交pull requests一起完善。

包括您Path.DirectorySeparatorChar的建议，可以直接提交pull requests。虽然这个作为半开源项目，本身就没办法跨平台（核心dll闭源，linux上没法直接移植），但是您的建议还是很不错的。
另外，如有需要定制开发需要可以通过商业合作方式联系，本项目客户端版、java web版均有成熟、商用化闭源产品。
开源的c#版本很多地方可拓展性比较差。java版使用了模块化、build风格来设计，提供了一个sdk包，查重算法、查重报告可以使用默认的，也可以通过实现接口来直接定制化。

另外说下，麻烦您仔细看下readme。线程数问题、查重报告和截图不一致问题这些reademe里写的都很清楚。查重报告和截图不一致是因为这个是开源版，截图是商用闭源版本。仔细读reademe，您问的这些问题都能解决，也节省您后续二次开发的时间。要不然readme那么长，我写来是干啥的呢

**Comment by tianlian0** [comment]
这个开源的c#版本很多地方可拓展性比较差。java版使用了模块化、build风格来设计，提供了一个sdk包，查重算法、查重报告可以使用默认的，也可以通过实现接口来直接定制。

**Comment by tianlian0** [comment]
另外说下，麻烦您仔细看下readme。线程数问题、查重报告和截图不一致问题这些reademe里写的都很清楚。查重报告和截图不一致是因为这个是开源版，截图是商用闭源版本。仔细读reademe，您问的这些问题都能解决，也节省后续二次开发的时间。要不然readme那么长，我写来是干啥的呢

**Comment by Colin5887** [comment]
README是有完整阅读过的，但是里面并没有提及：

* 为什么不使用Parallel而是手动处理每一个线程的工作内容
* 为什么要暴露用户并不会修改的参数在界面中

不过我想我已经知道问题的答案了，谢谢您的回答

**Comment by tianlian0** [comment]
高级设置下面的内容是有用的 都是之前踩过的坑 后期如果你规模化用起来也许就能遇到了^_^
比如那个“转换后最小字节”，转换pdf格式的论文的时候个别文章会出错，pdfbox不报错但是转换出来的文件有问题，这种文件其中一个特点就是转换出来的文件大小很小，就可以直接设个阈值把这种转换失败的卡掉。其它几个也都有用的，你后边可以看看。
Parallel那个，我不会这个类的用法。之前版本的readme有写，c#我是现学现卖的，只是因为它能拖拽UI用起来方便，没系统学过这个语言。后面把这段从readme里删了。如果您认为用Parallel更好的话可以帮忙修改下提交个pull requests啥的。

**Comment by Colin5887** [comment]
好的，谢谢您的解答，我这里如果开发完毕，确认没有问题的话，会找时间把修改合并到的项目里的

**Comment by Colin5887** [comment]
Parallel是C#的并发处理功能，会自动分配多个线程，自动并行处理。有点类似于C++的`OpenMP`的机制
