### ISSUE TITLE
查重过程软件闪退

### ISSUE THREAD

**Issue by qjh82353252** [tianlian0/paper_checking_system#12]
想问一下，我在纵向查重的过程中，进度条进行到一半会闪退，请问是什么原因？

**Comment by tianlian0** [comment]
如果是进度条刚走了一点点就闪退的话，参照“安装使用教程”下面有个“报错排除”排除一下。
如果是在中间闪退的话，说明前面有一部分成功了，遇到某一个文件报错了。一般是由于论文库中的论文，文件名中包含特殊字符（不可见字符、特殊的空格、奇怪的符号之类的），检查一些文件名吧。或者存在一些后缀是txt但是实际上不是文本文件的奇怪文件。可以打断点快速定位一下哪个文件出了问题。

**Comment by qjh82353252** [comment]
试了一下debug版本编译出来可以正常生成报告，但是纵向查重的结果永远都是0，不知道是什么原因。

**Comment by tianlian0** [comment]
你没添加论文库呗。没论文库当然是0
