### ISSUE TITLE
Program.cs: Invalid expression term "bool" & Syntax error, ',' expacted

### ISSUE THREAD

**Issue by AilvenLiu** [tianlian0/paper_checking_system#13]
win10, vs2015; 
尝试生成项目，报错：
Invalid expression term "bool";
 Syntax error, ',' expected; 
定位program.cs, 19行。

**Comment by AilvenLiu** [comment]
定位于下面一行：
System.Threading.Mutex instance = new System.Threading.Mutex(true, "CachongSingleStart0.9", out bool createdNew);

**Comment by AilvenLiu** [comment]
已解决

**Comment by tianlian0** [comment]
是不是.Net Framework版本不兼容导致的呢，我这边开发用的是4.6
