### ISSUE TITLE
vs编译过程中总是报错

### ISSUE THREAD

**Issue by ltf1469** [tianlian0/paper_checking_system#14]
![465D0F226EF977EAAFD460F1BA535838](https://user-images.githubusercontent.com/61586260/85575007-cd469e00-b669-11ea-8c42-c2e847948da0.jpg)

**Comment by ltf1469** [comment]
以下是具体报错内容：
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2701,5): warning MSB3283: 找不到类型库“Microsoft.Office.Core”的包装器程序集。请验证 (1) 是否已正确注册 COM 组件，以及 (2) 目标平台与 COM 组件的位数是否相同。例如，如果 COM 组件为 32 位，目标平台就不能为 64 位。
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2701,5): warning MSB3283: 找不到类型库“Microsoft.Office.Interop.Word”的包装器程序集。请验证 (1) 是否已正确注册 COM 组件，以及 (2) 目标平台与 COM 组件的位数是否相同。例如，如果 COM 组件为 32 位，目标平台就不能为 64 位。

**Comment by tianlian0** [comment]
我这边看了一下。
先说解决方法：在项目引用里把两个Microsoft.Office的引用移除然后再编译应该就行了。
错误原因：这两个Microsoft.Office的引用对应的Office位版本和你电脑上的不一样（引用了32位你安装的是64位，或者引用的54位你安装的32位）。
为什么直接删掉可以解决这个问题？这两个引用是开发早期的时候引用进去的，后期没有用到但是忘记移除了。后面更新代码的时候会进行移除。

**Comment by tianlian0** [comment]
目前最新的代码已对该问题进行了修复
