### ISSUE TITLE
为什么完全相同的文档得到的重复率会是0

### ISSUE THREAD

**Issue by iguxiaobei** [tianlian0/paper_checking_system#16]
如题，我故意弄了两个完全相同的文档，得出来的重复率是0
直接测试代码

int res = PaperManager.real_check(checkThreshold, threadCount, i, RunningEnv.ProgramParam.SecurityKey, RunningEnv.ProgramParam.ToCheckTxtPaperPath, RunningEnv.ProgramParam.TxtPaperSourcePath, RunningEnv.ProgramParam.ReportPath, RunningEnv.ProgramParam.ReportDataPath)

得到的res也是0

**Comment by iguxiaobei** [comment]
知道了，同名文件直接跳过了。

**Comment by 446496314mb** [comment]
您的代码里paper_checking.exe有这个文件吗
