### ISSUE TITLE
可以考虑增加模块化功能，生成报告的模板可以修改，能生成PDF文件

### ISSUE THREAD

**Issue by seven2017** [tianlian0/paper_checking_system#2]
大佬可以考虑增加模块化功能，生成报告的模板可以修改，报告里尽量能保持论文原始格式标红，查重报告如果可以生成PDF文件更棒棒了~

**Comment by tianlian0** [comment]
支持模板改动较大，后期有空可以考虑。保留原格式功能在随后两次更新内增加。导出PDF报告功能在评估中。

**Comment by seven2017** [comment]
可以在源码里面提供一个模版文件，改好模版再生成程序，生成pdf或者网页文件都可以~还有pdfbox更新v2.0.16了，大佬加油~~~

**Comment by tianlian0** [comment]
我们开发的Java查重SDK 0.3.8以上版本已支持查重报告样式定制化，详情参考链接：https://xincheck.com/?id=16
