### ISSUE TITLE
编译时出现错误：没有GetText方法

### ISSUE THREAD

**Issue by realyyh** [tianlian0/paper_checking_system#3]
错误	1	'Spire.Doc.Document' does not contain a definition for 'GetText' and no extension method 'GetText' accepting a first argument of type 'Spire.Doc.Document' could be found (are you missing a using directive or an assembly reference?)	C:\Users\Administrator\Desktop\paper_checking_system-master\paper_checking\MainForm.cs	53	24	paper_checking
![捕获](https://user-images.githubusercontent.com/55473929/65110675-a9379b80-da0b-11e9-9964-041d74d7269b.PNG)

环境是VS2012

**Comment by tianlian0** [comment]
请在NuGet中检查项目中是否正确安装了Spire.Doc并已更新至最新版本（7.9.0）。
