### ISSUE TITLE
编译时错误：has a higher version than referenced assembly

### ISSUE THREAD

**Issue by realyyh** [tianlian0/paper_checking_system#4]
错误	6	Assembly 'pdfbox-app, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' uses 'IKVM.OpenJDK.Core, Version=8.1.5717.0, Culture=neutral, PublicKeyToken=13235d27fcbfff58' which has a higher version than referenced assembly 'IKVM.OpenJDK.Core, Version=7.2.4630.5, Culture=neutral, PublicKeyToken=13235d27fcbfff58'	C:\Users\Administrator\Desktop\paper_checking_system-master\paper_checking\pdfbox-app.dll	paper_checking

**Comment by tianlian0** [comment]
需要IKVM8.1，这个报错显示你当前使用的是IKVM7.2。
项目的packages.config里已经配置了8.1版本的IKVM，如果缺失vs应该会自动下载，不太清楚你这个为什么仍然使用了7.2，是否手工修改了？
建议尝试：在NuGet中更新IKVM至最新版。
