### ISSUE TITLE
“以下论文出现错误，请检查”

### ISSUE THREAD

**Issue by realyyh** [tianlian0/paper_checking_system#5]
输入检测的所有论文都出现错误。
使用office2010另存过，也尝试转成pdf，依旧出错。甚至转成txt之后依旧报错。

![捕获](https://user-images.githubusercontent.com/55473929/65310527-193b5280-dbc1-11e9-9f32-0509ea287626.PNG)

**Comment by tianlian0** [comment]
1、代码中对论文的最少字数和去图后文件的最小大小有默认限制，低于限制会报错。如想不希望有限制可在代码中自行取消。
2、如果不是1中的问题，请提供一下必要的编译和运行环境信息、详细操作步骤和测试用例以让我进行测试和问题复现。
3、同时您可fork项目自行debug尝试修复，修复后您可提出代码合并请求。

**Comment by realyyh** [comment]
感谢！确实因为论文转换后最小大小的限制，修改后可以正常处理。
