### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by pbpf** [tianlian0/paper_checking_system#6]
1. 查重文件夹是否能缓存一下，每次都输入很麻烦
2. xc_core.exe 是否考虑开源？我想将查重系统直接嵌入word。

**Comment by tianlian0** [comment]
1、暂不会修改为记录上一次文件夹位置。目前生产环境中暂没有用户未反馈此需求，推断需求量不大，有更多用户反馈将会进行修改。如有个人需求可以自行修改配置文件部分的代码，将上一次路径写入配置文件，启动时读取即可。
2、xc_core模块暂不开源但并不影响你在其它软件中直接调用使用，调用方式参考c#源代码中的xc_core调用。
3、如确有xc_core的开源需要或软件定制化需求可通过readme中的商业合作联系方式联系。

**Comment by tianlian0** [comment]
现已增加查重文件夹退出后保存至配置文件，下次启动时自动读取的功能
