### ISSUE TITLE
建议增加对英文内容的重复检测

### ISSUE THREAD

**Issue by realyyh** [tianlian0/paper_checking_system#7]
用来检测学生提交的实验作业，里面有一些英文代码：
![捕获](https://user-images.githubusercontent.com/55473929/65567626-8405d880-df89-11e9-84e3-bb27007150a0.PNG)

发现检测的时候将英文全部删除，仅留下中文，感觉这样影响查重结果精确性。建议将英文内容保留并对英文也进行查重。

**Comment by tianlian0** [comment]
目前本项目的查重适用范围仅面向**简体中文论文**，代码查重和论文查重原理有所不同建议使用其它工具。也可继续关注我的GitHub，后续可能会有相关项目开源。如确有软件定制化需求可通过readme中的商业合作联系方式联系。

**Comment by realyyh** [comment]
> 目前本项目的查重适用范围仅面向**简体中文论文**，代码查重和论文查重原理有所不同建议使用其它工具。也可继续关注我的GitHub，后续可能会有相关项目开源。如确有软件定制化需求可通过readme中的商业合作联系方式联系。

请问有推荐的工具吗？
