### ISSUE TITLE
请问什么情况

### ISSUE THREAD

**Issue by ch656409110** [tianlian0/paper_checking_system#8]
待比较和比较的文件夹同一个，结果重复率为0，不管什么方式比较，返回都是0，是我操作不对吗？

**Comment by ch656409110** [comment]
现在是纵向查重不行，永远是0，横向查重感觉是那么回事了。没有报错。是否需要其他操作。

**Comment by tianlian0** [comment]
测试了一下，没有出现您提到的问题。

**Comment by ch656409110** [comment]
> 测试了一下，没有出现您提到的问题。

我是微信问你的那个，请问是用我发的论文吗，或者把你测试论文发我看看，因为现在不知道哪里不对

**Comment by ch656409110** [comment]
> 测试了一下，没有出现您提到的问题。

我是微信问你的那个，请问是用我发的论文吗，或者把你测试论文发我看看，因为现在不知道哪里不对，感谢

**Comment by tianlian0** [comment]
为了避免在查重时匹配到论文原文导致重复率100%的情况，待查论文不会和论文库中文件名相同的论文进行查重。你可以检查下是不是这个原因。

**Comment by ch656409110** [comment]
已解决，感谢。

我看截图有进度条，是收费版本吗？有没有意向做web版的，价格怎么样？

**Comment by tianlian0** [comment]
嗯，收费版的定制功能。
