### ISSUE TITLE
无法加载paper_check.dll

### ISSUE THREAD

**Issue by kjf4096** [tianlian0/paper_checking_system#9]
/*
         * 调用动态链接库方法的包装方法
         */
        private void RealCheckShell(object thread_payload)
        {
            //获取单数
            string[] part_param = (string[])thread_payload;
            int res = real_check(part_param[0], part_param[1], part_param[2], part_param[3], part_param[4], part_param[5], part_param[6], part_param[7]);
            //如果动态链接库异常返回值

System.DllNotFoundException:“无法加载 DLL“paper_check.dll”: 找不到指定的模块。 (异常来自 HRESULT:0x8007007E)。”

![image](https://user-images.githubusercontent.com/48580700/72202779-6f990d80-349e-11ea-95f4-d3a29fa4d5d3.png)

**Comment by tianlian0** [comment]
经测试没有复现此问题。可以详细说明以下使用环境、IDE版本以及详细的操作步骤我来尝试复现。
另外，报错提示找不到paper_check.dll，你可以尝试手工将这个dll复制到和可执行文件同一目录下。

**Comment by kjf4096** [comment]
win7 64位，vs2017

问题签名:
  问题事件名称:	CLR20r3
  问题签名 01:	paper_checking.exe
  问题签名 02:	0.9.0.0
  问题签名 03:	5e19af48
  问题签名 04:	paper_checking
  问题签名 05:	0.9.0.0
  问题签名 06:	5e19af48
  问题签名 07:	4d
  问题签名 08:	8
  问题签名 09:	System.DllNotFoundException
  OS 版本:	6.1.7601.2.1.0.256.1
  区域设置 ID:	2052
  其他信息 1:	467e
  其他信息 2:	467ea9d39023a3ee39ec9d30ae4e1dd4
  其他信息 3:	ac9c
  其他信息 4:	ac9c3f93d84e9a5563b18e49ac42278d

**Comment by kjf4096** [comment]
![image](https://user-images.githubusercontent.com/48580700/72204217-70d33600-34b0-11ea-85c6-d55e0154eb65.png)

**Comment by tianlian0** [comment]
报错提示找不到paper_check.dll，尝试手工将dll复制到和可执行文件同一目录下试试。

**Comment by kjf4096** [comment]
本来就在一个目录下
![image](https://user-images.githubusercontent.com/48580700/72204605-ee994080-34b4-11ea-8de2-82c27d36d4d5.png)

**Comment by kjf4096** [comment]
![2](https://user-images.githubusercontent.com/48580700/72204696-b3e3d800-34b5-11ea-8e42-4b34194763d5.jpg)

**Comment by tianlian0** [comment]
![image](https://user-images.githubusercontent.com/25587822/72207208-c704a100-34d1-11ea-9fe2-fd3a7fbd3a02.png)
初步推断是因为缺少这个c++库。近期我会更新一个静态编译的dll以摆脱对这个库的依赖。临时解决方案可以先安装一下这个库。

**Comment by kjf4096** [comment]
已解决，感谢。
